name: Build IPA

on:
    workflow_dispatch:
        inputs:
            app_name:
                description: 'Application Name'
                required: true
                default: 'PakePlusApp'
            bundle_id:
                description: 'Bundle Identifier'
                required: true
                default: 'com.pakeplus.app'
            description:
                description: 'Application Description'
                required: false
                default: ''
            version:
                description: 'App Version'
                required: true
                default: '1.0.0'

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Xcode
              uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: '16.4'

            - uses: pnpm/action-setup@v3
              with:
                  version: latest

            - name: Sync node version and setup cache
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: Init Project Config
              run: |
                  pnpm install
                  pnpm pp:worker

            - name: Generate AppIcon
              run: |
                  echo "Installing appicon tool..."
                  brew install Nonchalant/appicon/appicon
                  echo "Generating AppIcon..."
                  # Check if app-icon.png exists, otherwise use a default
                  if [ -f app-icon.png ]; then
                      appicon app-icon.png --output-path ./PakePlus/Assets.xcassets/AppIcon.appiconset
                  else
                      echo "app-icon.png not found, using default icon."
                      # You might want to copy a default icon here or handle it in Xcode
                  end

            - name: Prepare custom files (if any)
              run: |
                  if [ -d "local_app" ]; then
                      echo "Copying custom files to PakePlus project..."
                      cp -R local_app PakePlus/
                  else
                      echo "No custom files found."
                  fi

            - name: Build for Release
              run: |
                  xcodebuild -project PakePlus.xcodeproj -scheme PakePlus -configuration Release -sdk iphoneos \
                    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
                    PRODUCT_BUNDLE_IDENTIFIER="${{ github.event.inputs.bundle_id }}" \
                    PRODUCT_NAME="${{ github.event.inputs.app_name }}"

            - name: Package IPA
              run: |
                  APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "${{ github.event.inputs.app_name }}.app" | grep Release-iphoneos | head -n 1)
                  echo "APP_PATH is $APP_PATH"
                  mkdir -p Payload
                  cp -R "$APP_PATH" Payload/
                  NAME="${{ github.event.inputs.app_name }}"
                  VERSION="${{ github.event.inputs.version }}"
                  zip -r "${NAME}-${VERSION}.ipa" Payload
                  mkdir -p export
                  mv "${NAME}-${VERSION}.ipa" export/

            - name: Publish IPA
              uses: softprops/action-gh-release@v1
              with:
                  files: export/${{ github.event.inputs.app_name }}-${{ github.event.inputs.version }}.ipa
                  tag_name: 'v${{ github.event.inputs.version }}'
                  name: '${{ github.event.inputs.app_name }} v${{ github.event.inputs.version }}'
                  body: '${{ github.event.inputs.description }}'
                  draft: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

